language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: LUS91DvYUcRJYMYBCmobUzdHPbYvvhW6Fs/5mKrOuHUXbCLfxrHbkb9DdPYqKhFOmNxEaFxZVKcTWjpcL2L4NmwfXin3SkB3tlnWeBT+COF5USkFGYYn6/ItP+GdxpXtMDSB12dqV4ej1mi07W9aS6594iRkB16kEhxvoIriIrCzp3FYH+I4rU494cUMcCccf72OybOFIRVgoesiLeT83Q8nsxgDLejghmSrQTI2luZAGleu7XBo+2VVme2S80BViNfec6QbySZzozVSIcYvbO4lLCoTenuIVAXo7+eg5MomjF5iHkng5q3MqmkTxwZUC42vYNzqg9T9sQMwXj/99QsODTesxd4Zn/zRVKh0GpnNYuIkCbEyKNt9vDQCx+z3gFVfcRgozWg4iK2K2CQlPoVVoz68tl9HCxk994MJhV/IDq+GSQnu9BhOtyHjkejqYG/dwsK/qeQZqtAlkzf4afuWPTb8WwS4R7uPHpYbJxNLZks9I3pn5NypAeQYrA/vKepgukcZABXeAEsze3A5NdkWXgobrZyjqRXW5M1eGaWFAXTSpIHcy4qtVkvvXrtqSyUUpoSpt8JWCcXguzdt8iY4gp5pVeaaymFXtb5uWZWWV9W4KcRvdI3ar6rRdGMeCzx+wrc1UbvhOdgTEnx0VAf0v8SBvw7qM7iZfhkQjDc=
  - secure: X/EvmKD2uozEHcZ2sGwLH1UhErwKA+i+mMYnpYoA8DZwl/N2ooyD7D2OEJAM3CNe3A8elPun6fW7iUpD2N1O6FGe1d4POOm/39heUAU+uda/XkN2rLiMz/zM6SfAq0yMs2cI7o5gQm07RvCs8Jxeh6lnUN8WtzYVCyySHxvadyiOIZY8Kv0YH7nbvzMVGYabmxSBUdQ8PsgyU0AjFfK3vJw6Psf/E7W0uYJ8mCmd6g6iC7CNKkVcm+8igGFZw1e9Dm5dDL2UGi2P60bm7ovanReNKyy+k+v0DOZRvKz3uy7MCEK3q5RZyi8GFEgtGAMLCT0W+GD/qpSnqOAJYxXfyji37IDcyGKIw8BZOaw+tlMVKHTd3UiyUunGPFx70KpaqumcGE0y9sTz2DRK6DdQJ3mzeYr7By5LPlOpU7D/c/6bwUDwualDSjx26gdZWbeXBKvGMlpC5V02t5G8a9TYmgqOVNskzjcgHm+B85IABFgDOXqtuDi3n60rkSYoHP6hGyKvfMeQX0ytXnTCLZOPTgqTF2BcWriO5i7uy1SxXfKuZlXLoD17Qdg0JL1pCKaK2J2MdRUjqW1LBNomktO9dKo6U5QqbnPx0+Xt8XPngK3pT2Q10wBvLYhiWPYlJckMZRVQvkNtkNCz8+DNM5Z0WkXZqZjRaNPi/gdlbUSLszE=
